# Generated by Django 5.1.1 on 2024-09-30 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=35)),
                ('user', models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_category', to='backend.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_category', to='backend.shop')),
            ],
            options={
                'verbose_name': 'Категория магазина',
                'verbose_name_plural': 'Список категорий магазинов',
            },
        ),
        migrations.DeleteModel(
            name='ConfirmEmailToken',
        ),
        migrations.AddConstraint(
            model_name='shopcategory',
            constraint=models.UniqueConstraint(fields=('shop', 'category'), name='unique_shop_category'),
        ),
    ]
